import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

const translations = {
  Français: {
    welcome: 'Bienvenue chez WQAFT',
    login: 'Connexion',
    register: 'Créer un compte WQAFT',
    emailOrPhone: 'Email ou numéro de téléphone',
    password: 'Mot de passe',
    forgotPassword: 'Mot de passe oublié ?',
    send: 'Envoyer',
    sendMessage: 'Envoyer',
    details: 'Voir détails',
    contact: 'Contact',
    contacts: 'Contacts',
    messages: 'Messages',
    profile: 'Mon Profil',
    settings: 'Paramètres',
    logout: 'Se déconnecter',
    myLocation: 'Votre position',
    mapTitle: 'Carte',
    breakdownFormTitle: 'Formulaire de panne',
    breakdownDescription: 'Décrivez votre panne en détail...',
    vehicleType: 'Type de véhicule',
    locationPlaceholder: 'Localisation exacte',
    noteSent: 'Votre demande a bien été envoyée aux mécaniciens proches.',
    requestSent: 'Demande envoyée',
    acceptPrice: 'Accepter le prix',
    negotiatePrice: 'Négocier le prix',
    refusePrice: 'Refuser le prix',
    pinMessage: 'Épingler',
    deleteMessage: 'Supprimer',
    addInformation: 'Ajouter des informations',
    editInformation: 'Modifier',
    deleteAccount: 'Supprimer le compte',
    notifications: 'Notifications',
    locationAccess: 'Localisation',
    themeLight: 'Mode Clair',
    themeDark: 'Mode Sombre',
    language: 'Langue',
    distanceUnit: 'Unité de distance',
    pushNotifications: 'Notifications push',
    locationSharing: 'Partage de localisation',
    resetPassword: 'Réinitialiser le mot de passe',
    back: 'Retour',
    reportBreakdown: 'Je signale ma panne',
    messageDetails: 'Détails du contact',
    call: 'Appeler',
    nearbyMechanics: 'Mécaniciens proches',
    saveChanges: 'Sauvegarder les modifications',
    profileUpdated: 'Profil mis à jour',
    accountDeleted: 'Compte supprimé',
    fullName: 'Nom complet',
    firstName: 'Prénom',
    lastName: 'Nom',
    phone: 'Téléphone',
    city: 'Ville',
    address: 'Adresse',
    specialty: 'Spécialité',
    role: 'Rôle',
    locationDetected: 'Position détectée',
    mechanics: 'Mécaniciens',
    requests: 'Demandes',
    home: 'Accueil',
    interventions: 'Interventions',
    chooseProfile: 'Choisissez votre profil',
    automobiliste: 'Automobiliste',
    mecanicien: 'Mécanicien',
    automobilisteDesc: 'Je cherche un mécanicien en urgence.',
    mecanicienDesc: 'Je propose mes services de dépannage.',
    createAccount: 'Créer mon compte',
    alreadyHaveAccount: 'Vous avez déjà un compte ?',
    signIn: 'Se connecter',
    vehicleInfo: 'Informations véhicule',
    profInfo: 'Informations professionnelles',
    garageName: 'Nom du garage',
    experience: 'Expérience',
    authorization: 'Autorisation',
    import: 'Importer',
    brand: 'Marque',
    model: 'Modèle',
    licensePlate: 'Immatriculation',
    gearbox: 'Boîte de vitesse',
    manual: 'Manuelle',
    automatic: 'Automatique',
    years: 'ans',
    year: 'an',
    appearance: 'Apparence',
    configuration: 'Configuration',
    personalAccount: 'Compte Personnel',
    accountDetails: 'Détails du compte',
    expertise: 'Expertise Métier',
    specialtyLabel: 'Spécialité',
    garage: 'Garage',
    resetData: 'Réinitialiser les données',
    save: 'Enregistrer',
    editProfile: 'Modifier Profil',
    cancel: 'Annuler',
    addVehicle: 'Ajouter Véhicule',
    addInfos: 'Ajouter Infos',
    pneuCreve: 'Pneu crevé',
    batterieDechargee: 'Batterie déchargée',
    panneMoteur: 'Panne moteur',
    panneEssence: 'Panne d’essence',
    surchauffeMoteur: 'Surchauffe moteur',
    problemeFreins: 'Problème de freins',
    boiteVitesses: 'Boîte de vitesses',
    problemeElectrique: 'Problème électrique',
    accident: 'Accident',
    clesEnfermees: 'Clés enfermées',
    problemeDemarrage: 'Problème de démarrage',
    fuiteHuile: 'Fuite d’huile',
    fuiteLiquide: 'Fuite de liquide',
    autre: 'Autre',
    launchAlert: "Lancer l'alerte",
    assistExpress: 'Assistance Express',
    problemDetails: 'Détails du problème',
    typeBreakdown: 'Type de panne',
    yourPosition: 'Votre position',
    descPhotos: 'Description & Photos',
    addPhoto: 'Ajouter une photo',
    nearbyMechanicsAlert: 'Les mécaniciens à proximité recevront votre demande immédiatement.',
    sendingRequest: 'Envoi de la demande en cours...',
    reconnectToRequest: 'Veuillez vous reconnecter pour envoyer une demande.',
    requestSentSuccess: 'Votre demande a bien été envoyée. Des offres arrivent bientôt.',
    errorSending: 'Une erreur est survenue lors de l’envoi.',
    serverError: 'Impossible de contacter le serveur.',
    offersInProgress: 'Offres en cours...',
    checkMessages: 'Consultez vos messages pour voir les propositions.',
    youAreHere: 'Vous êtes ici',
    iAmDown: 'Je suis en panne',
    conversations: 'Conversations',
    discussion: 'Discussion',
    searchPlaceholder: 'Chercher',
    writeMessage: 'Écrire un message...',
    confirmDelete: 'Confirmer la suppression',
    deleteConversationMsg: 'Voulez-vous vraiment supprimer cette conversation ?',
    accept: 'Accepter',
    refuse: 'Refuser',
    negotiate: 'Négocier',
    proposals: 'Propositions',
    all: 'Tous',
    mechanicsRecommended: 'Mécaniciens recommandés',
    searchByName: 'Rechercher par nom',
    message: 'Message',
    detailsMechanic: 'Détails du mécanicien',
    mecanique: 'Mécanique',
    electricite: 'Électricité',
    vidange: 'Vidange',
    diagnostic: 'Diagnostic',
    batterie: 'Batterie',
    pneus: 'Pneus',
    close: 'Fermer',
    sendAMessage: 'Envoyer un message',
    selectConversation: 'Sélectionnez une conversation',
    confirmReset: 'Voulez-vous vraiment réinitialiser ces informations ?',
  },
  Anglais: {
    welcome: 'Welcome to WQAFT',
    login: 'Login',
    register: 'Create a WQAFT account',
    emailOrPhone: 'Email or phone number',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    send: 'Send',
    sendMessage: 'Send',
    details: 'View details',
    contact: 'Contact',
    messages: 'Messages',
    profile: 'My Profile',
    settings: 'Settings',
    logout: 'Logout',
    myLocation: 'Your location',
    mapTitle: 'Map',
    breakdownFormTitle: 'Breakdown report',
    breakdownDescription: 'Describe your issue in detail...',
    vehicleType: 'Vehicle type',
    locationPlaceholder: 'Exact location',
    noteSent: 'Your request has been sent to nearby mechanics.',
    requestSent: 'Request sent',
    acceptPrice: 'Accept price',
    negotiatePrice: 'Negotiate price',
    refusePrice: 'Refuse price',
    proposals: 'Proposals',
    pinMessage: 'Pin',
    deleteMessage: 'Delete',
    addInformation: 'Add information',
    editInformation: 'Edit',
    deleteAccount: 'Delete account',
    notifications: 'Notifications',
    locationAccess: 'Location',
    themeLight: 'Light mode',
    themeDark: 'Dark mode',
    language: 'Language',
    distanceUnit: 'Distance unit',
    pushNotifications: 'Push notifications',
    locationSharing: 'Location sharing',
    resetPassword: 'Reset password',
    back: 'Back',
    reportBreakdown: 'Report my breakdown',
    messageDetails: 'Contact details',
    call: 'Call',
    nearbyMechanics: 'Nearby mechanics',
    saveChanges: 'Save changes',
    profileUpdated: 'Profile updated',
    accountDeleted: 'Account deleted',
    fullName: 'Full name',
    firstName: 'First name',
    lastName: 'Last name',
    phone: 'Phone',
    city: 'City',
    address: 'Address',
    specialty: 'Specialty',
    garageName: 'Garage',
    role: 'Role',
    locationDetected: 'Location detected',
    mechanics: 'Mechanics',
    requests: 'Requests',
    home: 'Home',
    interventions: 'Interventions',
    chooseProfile: 'Choose your profile',
    automobiliste: 'Driver',
    mecanicien: 'Mechanic',
    automobilisteDesc: 'I am looking for an emergency mechanic.',
    mecanicienDesc: 'I offer breakdown services.',
    createAccount: 'Create my account',
    alreadyHaveAccount: 'Already have an account?',
    signIn: 'Sign in',
    vehicleInfo: 'Vehicle information',
    profInfo: 'Professional information',
    garageName: 'Garage name',
    experience: 'Experience',
    authorization: 'Authorization',
    import: 'Import',
    brand: 'Brand',
    model: 'Model',
    licensePlate: 'License plate',
    gearbox: 'Gearbox',
    manual: 'Manual',
    automatic: 'Automatic',
    years: 'years',
    year: 'year',
    appearance: 'Appearance',
    configuration: 'Configuration',
    personalAccount: 'Personal Account',
    accountDetails: 'Account Details',
    expertise: 'Professional Expertise',
    specialtyLabel: 'Specialty',
    garage: 'Garage',
    resetData: 'Reset Data',
    save: 'Save',
    editProfile: 'Edit Profile',
    cancel: 'Cancel',
    addVehicle: 'Add Vehicle',
    addInfos: 'Add Infos',
    city: 'City',
  },
  Arabe: {
    welcome: 'مرحبًا بك في WQAFT',
    login: 'تسجيل الدخول',
    register: 'إنشاء حساب WQAFT',
    emailOrPhone: 'البريد الإلكتروني أو رقم الهاتف',
    password: 'كلمة المرور',
    forgotPassword: 'نسيت كلمة المرور؟',
    send: 'إرسال',
    sendMessage: 'إرسال',
    details: 'عرض التفاصيل',
    contact: 'الاتصال',
    messages: 'الرسائل',
    profile: 'ملفي',
    settings: 'الإعدادات',
    logout: 'تسجيل الخروج',
    myLocation: 'موقعي',
    mapTitle: 'الخريطة',
    breakdownFormTitle: 'نموذج العطل',
    breakdownDescription: 'اختر مشكلتك بالتفصيل...',
    vehicleType: 'نوع السيارة',
    locationPlaceholder: 'الموقع الدقيق',
    noteSent: 'تم إرسال طلبك إلى الفنيين القريبين.',
    requestSent: 'تم إرسال الطلب',
    acceptPrice: 'قبول السعر',
    negotiatePrice: 'التفاوض على السعر',
    refusePrice: 'رفض السعر',
    pinMessage: 'تثبيت',
    deleteMessage: 'حذف',
    addInformation: 'إضافة معلومات',
    editInformation: 'تعديل',
    deleteAccount: 'حذف الحساب',
    notifications: 'الإشعارات',
    locationAccess: 'الموقع',
    themeLight: 'الوضع الفاتح',
    themeDark: 'الوضع الداكن',
    language: 'اللغة',
    distanceUnit: 'وحدة المسافة',
    pushNotifications: 'إشعارات الدفع',
    locationSharing: 'مشاركة الموقع',
    resetPassword: 'إعادة تعيين كلمة المرور',
    back: 'رجوع',
    reportBreakdown: 'أبلغ عن عطل',
    messageDetails: 'تفاصيل الاتصال',
    call: 'اتصال',
    nearbyMechanics: 'الفنيون القريبون',
    saveChanges: 'حفظ التغييرات',
    profileUpdated: 'تم تحديث الملف الشخصي',
    accountDeleted: 'تم حذف الحساب',
    fullName: 'الاسم الكامل',
    firstName: 'الاسم',
    lastName: 'اللقب',
    phone: 'الهاتف',
    city: 'المدينة',
    address: 'العنوان',
    specialty: 'التخصص',
    garageName: 'الورشة',
    role: 'الدور',
    locationDetected: 'تم اكتشاف الموقع',
    mechanics: 'الفنيون',
    requests: 'الطلبات',
    home: 'الرئيسية',
    interventions: 'التدخلات',
    chooseProfile: 'اختر ملفك الشخصي',
    automobiliste: 'سائق',
    mecanicien: 'ميكانيكي',
    automobilisteDesc: 'أبحث عن ميكانيكي في حالة طوارئ.',
    mecanicienDesc: 'أقدم خدمات إصلاح الأعطال.',
    createAccount: 'إنشاء حسابي',
    alreadyHaveAccount: 'هل لديك حساب بالفعل؟',
    signIn: 'تسجيل الدخول',
    vehicleInfo: 'معلومات السيارة',
    profInfo: 'معلومات مهنية',
    garageName: 'اسم الورشة',
    experience: 'الخبرة',
    authorization: 'التفويض',
    import: 'استيراد',
    brand: 'الماركة',
    model: 'الموديل',
    licensePlate: 'رقم اللوحة',
    gearbox: 'علبة التروس',
    manual: 'يدوي',
    automatic: 'أوتوماتيكي',
    years: 'سنوات',
    year: 'سنة',
    appearance: 'المظهر',
    configuration: 'الإعدادات',
    personalAccount: 'الحساب الشخصي',
    accountDetails: 'تفاصيل الحساب',
    expertise: 'الخبرة المهنية',
    specialtyLabel: 'التخصص',
    garage: 'الورشة',
    resetData: 'إعادة تعيين البيانات',
    save: 'حفظ',
    editProfile: 'تعديل الملف الشخصي',
    cancel: 'إلغاء',
    addVehicle: 'إضافة سيارة',
    addInfos: 'إضافة معلومات',
    cityLabel: 'المدينة',
  },
  Espagnol: {
    welcome: 'Bienvenido a WQAFT',
    login: 'Iniciar sesión',
    register: 'Crear cuenta WQAFT',
    emailOrPhone: 'Correo o teléfono',
    password: 'Contraseña',
    forgotPassword: '¿Olvidaste tu contraseña?',
    send: 'Enviar',
    sendMessage: 'Enviar',
    details: 'Ver detalles',
    contact: 'Contacto',
    messages: 'Mensajes',
    profile: 'Mi Perfil',
    settings: 'Ajustes',
    logout: 'Cerrar sesión',
    myLocation: 'Tu ubicación',
    mapTitle: 'Mapa',
    breakdownFormTitle: 'Reporte de avería',
    breakdownDescription: 'Describe tu problema...',
    vehicleType: 'Tipo de vehículo',
    locationPlaceholder: 'Ubicación exacta',
    noteSent: 'Tu solicitud ha sido enviada.',
    requestSent: 'Solicitud enviada',
    acceptPrice: 'Aceptar precio',
    negotiatePrice: 'Negociar',
    refusePrice: 'Rechazar',
    pinMessage: 'Anclar',
    deleteMessage: 'Eliminar',
    addInformation: 'Añadir información',
    editInformation: 'Editar',
    deleteAccount: 'Eliminar cuenta',
    notifications: 'Notificaciones',
    locationAccess: 'Ubicación',
    themeLight: 'Modo claro',
    themeDark: 'Modo oscuro',
    language: 'Idioma',
    distanceUnit: 'Unidad de distancia',
    pushNotifications: 'Notificaciones push',
    locationSharing: 'Compartir ubicación',
    resetPassword: 'Restablecer contraseña',
    back: 'Volver',
    reportBreakdown: 'Informar avería',
    messageDetails: 'Detalles de contacto',
    call: 'Llamar',
    nearbyMechanics: 'Mecánicos cercanos',
    saveChanges: 'Guardar cambios',
    profileUpdated: 'Perfil actualizado',
    accountDeleted: 'Cuenta eliminada',
    fullName: 'Nombre completo',
    firstName: 'Nombre',
    lastName: 'Apellido',
    phone: 'Teléfono',
    city: 'Ciudad',
    address: 'Dirección',
    specialty: 'Especialidad',
    garageName: 'Taller',
    role: 'Rol',
    locationDetected: 'Ubicación detectada',
    mechanics: 'Mecánicos',
    requests: 'Solicitudes',
    home: 'Inicio',
    interventions: 'Intervenciones',
    chooseProfile: 'Elige tu perfil',
    automobiliste: 'Conductor',
    mecanicien: 'Mecánico',
    automobilisteDesc: 'Busco un mecánico de emergencia.',
    mecanicienDesc: 'Ofrezco servicios de reparación.',
    createAccount: 'Crear mi cuenta',
    alreadyHaveAccount: '¿Ya tienes una cuenta?',
    signIn: 'Iniciar sesión',
    vehicleInfo: 'Información del vehículo',
    profInfo: 'Información profesional',
    garageName: 'Nombre del taller',
    experience: 'Experiencia',
    authorization: 'Autorización',
    import: 'Importar',
    brand: 'Marca',
    model: 'Modelo',
    licensePlate: 'Matrícula',
    gearbox: 'Caja de cambios',
    manual: 'Manual',
    automatic: 'Automática',
    years: 'años',
    year: 'año',
    appearance: 'Apariencia',
    configuration: 'Configuración',
    personalAccount: 'Cuenta Personal',
    accountDetails: 'Detalles de la cuenta',
    expertise: 'Pericia Profesional',
    specialtyLabel: 'Especialidad',
    garage: 'Taller',
    resetData: 'Restablecer datos',
    save: 'Guardar',
    editProfile: 'Editar Perfil',
    cancel: 'Cancelar',
    addVehicle: 'Añadir Vehículo',
    addInfos: 'Añadir Infos',
    cityLabel: 'Ciudad',
  },
  Italien: {
    welcome: 'Benvenuti in WQAFT',
    login: 'Accesso',
    register: 'Crea un account WQAFT',
    emailOrPhone: 'Email o telefono',
    password: 'Password',
    profile: 'Il mio profilo',
    settings: 'Impostazioni',
    logout: 'Disconnetti',
    home: 'Home',
    automobiliste: 'Autista',
    mecanicien: 'Meccanico',
    save: 'Salva',
    cancel: 'Annulla',
    language: 'Lingua',
  },
  Portugais: {
    welcome: 'Bem-vindo ao WQAFT',
    login: 'Entrar',
    register: 'Criar conta WQAFT',
    emailOrPhone: 'E-mail ou telefone',
    password: 'Senha',
    profile: 'Meu perfil',
    settings: 'Configurações',
    logout: 'Sair',
    home: 'Início',
    automobiliste: 'Motorista',
    mecanicien: 'Mecânico',
    save: 'Salvar',
    cancel: 'Cancelar',
    language: 'Idioma',
  },
  Chinois: {
    welcome: '欢迎来到 WQAFT',
    login: '登录',
    register: '创建 WQAFT 账户',
    emailOrPhone: '电子邮件或电话号码',
    password: '密码',
    profile: '我的个人资料',
    settings: '设置',
    logout: '登出',
    home: '首页',
    automobiliste: '司机',
    mecanicien: '技工',
    save: '保存',
    cancel: '取消',
    language: '语言',
  },
  Japonais: {
    welcome: 'WQAFTへようこそ',
    login: 'ログイン',
    register: 'WQAFTアカウントを作成',
    emailOrPhone: 'メールまたは電話番号',
    password: 'パスワード',
    profile: 'プロフィール',
    settings: '設定',
    logout: 'ログアウト',
    home: 'ホーム',
    automobiliste: 'ドライバー',
    mecanicien: '整備士',
    save: '保存',
    cancel: 'キャンセル',
    language: '言語',
  },
  Allemand: {
    welcome: 'Willkommen bei WQAFT',
    login: 'Anmelden',
    register: 'WQAFT-Konto erstellen',
    emailOrPhone: 'E-Mail oder Telefon',
    password: 'Passwort',
    forgotPassword: 'Passwort vergessen?',
    send: 'Senden',
    sendMessage: 'Senden',
    details: 'Details anzeigen',
    contact: 'Kontakt',
    messages: 'Nachrichten',
    profile: 'Mein Profil',
    settings: 'Einstellungen',
    logout: 'Abmelden',
    myLocation: 'Ihr Standort',
    mapTitle: 'Karte',
    breakdownFormTitle: 'Pannenbericht',
    breakdownDescription: 'Beschreiben Sie Ihr Problem...',
    vehicleType: 'Fahrzeugtyp',
    locationPlaceholder: 'Genauer Standort',
    noteSent: 'Ihre Anfrage wurde gesendet.',
    requestSent: 'Anfrage gesendet',
    acceptPrice: 'Preis akzeptieren',
    negotiatePrice: 'Verhandeln',
    refusePrice: 'Ablehnen',
    pinMessage: 'Anheften',
    deleteMessage: 'Löschen',
    addInformation: 'Information hinzufügen',
    editInformation: 'Bearbeiten',
    deleteAccount: 'Konto löschen',
    notifications: 'Benachrichtigungen',
    locationAccess: 'Standort',
    themeLight: 'Heller Modus',
    themeDark: 'Dunkler Modus',
    language: 'Sprache',
    distanceUnit: 'Entfernungseinheit',
    pushNotifications: 'Push-Benachrichtigungen',
    locationSharing: 'Standortfreigabe',
    resetPassword: 'Passwort zurücksetzen',
    back: 'Zurück',
    reportBreakdown: 'Panne melden',
    messageDetails: 'Kontaktdaten',
    call: 'Anrufen',
    nearbyMechanics: 'Mechaniker in der Nähe',
    saveChanges: 'Änderungen speichern',
    profileUpdated: 'Profil aktualisiert',
    accountDeleted: 'Konto gelöscht',
    fullName: 'Vollständiger Name',
    firstName: 'Vorname',
    lastName: 'Nachname',
    phone: 'Telefon',
    city: 'Stadt',
    address: 'Adresse',
    specialty: 'Fachgebiet',
    garageName: 'Werkstatt',
    role: 'Rolle',
    locationDetected: 'Standort erkannt',
    mechanics: 'Mechaniker',
    requests: 'Anfragen',
  },
};

const AppContext = createContext({
  language: 'Français',
  theme: 'dark',
  setLanguage: () => {},
  setTheme: () => {},
  toggleTheme: () => {},
  t: (key) => key,
});

export function AppProvider({ children }) {
  const [language, setLanguage] = useState('Français');
  const [theme, setTheme] = useState('dark');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('wqaft_language');
    const savedTheme = localStorage.getItem('wqaft_theme');
    if (savedLanguage && translations[savedLanguage]) setLanguage(savedLanguage);
    if (savedTheme) setTheme(savedTheme);
  }, []);

  useEffect(() => {
    localStorage.setItem('wqaft_language', language);
    localStorage.setItem('wqaft_theme', theme);
    if (theme === 'light') {
      document.documentElement.classList.add('light');
    } else {
      document.documentElement.classList.remove('light');
    }
    document.documentElement.dir = language === 'Arabe' ? 'rtl' : 'ltr';
  }, [language, theme]);

  const toggleTheme = () => setTheme(prev => prev === 'dark' ? 'light' : 'dark');

  const t = useMemo(() => {
    const current = translations[language] || translations.Français;
    return (key) => current[key] || key;
  }, [language]);

  return (
    <AppContext.Provider value={{ language, theme, setLanguage, setTheme, toggleTheme, t }}>
      {children}
    </AppContext.Provider>
  );
}

export function useApp() {
  return useContext(AppContext);
}
