export const carData = {
  'Toyota': ['Corolla', 'Yaris', 'Hilux', 'Rav4', 'Land Cruiser', 'C-HR', 'Prado', 'Auris'],
  'Renault': ['Clio', 'Captur', 'Megane', 'Kadjar', 'Kangoo', 'Master', 'Trafic', 'Express'],
  'Dacia': ['Logan', 'Sandero', 'Duster', 'Lodgy', 'Dokker', 'Jogger'],
  'Peugeot': ['208', '308', '2008', '3008', '5008', 'Partner', 'Rifter', 'Expert'],
  'BMW': ['Série 1', 'Série 3', 'Série 5', 'X1', 'X3', 'X5', 'X6', 'M3', 'M5'],
  'Mercedes-Benz': ['Classe A', 'Classe C', 'Classe E', 'Classe S', 'GLA', 'GLC', 'GLE', 'Vito'],
  'Volkswagen': ['Golf', 'Polo', 'Tiguan', 'Touareg', 'Passat', 'Caddy', 'Transporter', 'T-Roc'],
  'Ford': ['Fiesta', 'Focus', 'Ranger', 'Kuga', 'Transit', 'Mustang', 'EcoSport'],
  'Hyundai': ['i10', 'i20', 'i30', 'Tucson', 'Santa Fe', 'Accent', 'Creta', 'Elantra'],
  'Kia': ['Picanto', 'Rio', 'Sportage', 'Sorento', 'Ceed', 'K5', 'Niro'],
  'Fiat': ['500', 'Panda', 'Tipo', 'Doblo', 'Fiorino', 'Ducato'],
  'Opel': ['Corsa', 'Astra', 'Mokka', 'Grandland', 'Combo', 'Vivaro'],
  'Citroën': ['C3', 'C4', 'C5 Aircross', 'Berlingo', 'Jumpy', 'Jumper'],
  'Seat': ['Ibiza', 'Leon', 'Arona', 'Ateca', 'Tarraco'],
  'Skoda': ['Fabia', 'Octavia', 'Superb', 'Karoq', 'Kodiaq'],
  'Nissan': ['Micra', 'Qashqai', 'Juke', 'Navara', 'Patrol', 'X-Trail'],
  'Mazda': ['Mazda2', 'Mazda3', 'Mazda6', 'CX-3', 'CX-5', 'CX-30'],
  'Honda': ['Civic', 'Jazz', 'CR-V', 'HR-V', 'Accord'],
  'Suzuki': ['Swift', 'Jimny', 'Vitara', 'Celerio', 'Alto'],
  'Mitsubishi': ['L200', 'Pajero', 'Outlander', 'ASX', 'Eclipse Cross'],
  'Jeep': ['Renegade', 'Compass', 'Cherokee', 'Grand Cherokee', 'Wrangler'],
  'Land Rover': ['Range Rover', 'Range Rover Sport', 'Evoque', 'Discovery', 'Defender'],
  'Volvo': ['XC40', 'XC60', 'XC90', 'V40', 'S60', 'S90'],
  'Audi': ['A1', 'A3', 'A4', 'A6', 'Q3', 'Q5', 'Q7', 'Q8'],
  'Porsche': ['911', 'Cayenne', 'Macan', 'Panamera', 'Taycan'],
  'Chevrolet': ['Spark', 'Aveo', 'Cruze', 'Captiva', 'Optra'],
};

export const carBrands = Object.keys(carData).sort();
